### ISSUE TITLE
Tests for every function

### ISSUE THREAD

**Issue by callumrollo** [GliderToolsCommunity/GliderTools#101]
We are experiencing problems in other Issues that stem from a lack of tests.

I am by no means an expert on tests, but I propose a good starting point would be to write at least one test per function in the codebase. I have started doing this for the `physics` module.

If you have some testing experience, please chime in if this could be done more elegantly!

**Comment by jbusecke** [comment]
Just did that in #102, but its a band aid at most...

**Comment by jbusecke** [comment]
Also is this perhaps a duplicate of #6?

**Comment by callumrollo** [comment]
Good point, better to keep things focused in #6
