### ISSUE TITLE
Confused with git and pushing, maybe contributing guide needs some change? 

### ISSUE THREAD

**Issue by dhruvbalwada** [GliderToolsCommunity/GliderTools#108]
I have managed to confuse myself with git (yet again). Here is the problem:
a) I have a fork (https://github.com/dhruvbalwada/GliderTools) which hadn't had any contact with https://github.com/GliderToolsCommunity/GliderTools in a while. So to get the latest stuff, I did a pull request from the main GT to my fork (not sure if this was the best way to do this).
b) Now I have a fork that is 1 commit ahead of the https://github.com/dhruvbalwada/GliderTools.
c) So then I pulled all this to the repo on my computer, since I wanted to make some changes. I also set upstream
d) Then I checked out a branch, as is described in the contribution guide and made the changes.
e) However, now when I try to push this branch, I get the error:
```
(base) ➜  GliderTools git:(doc_update_rebase) git push
fatal: The current branch doc_update_rebase has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin doc_update_rebase
```
f) Obviously I cant set upstream as the place to push, I want to push to my fork. How do I do this?

Did I make some error that following the contributing guide is not working for me?

**Comment by dhruvbalwada** [comment]
I realized that all this was happening because I had a clone of this main repository on computer, and I was trying to mess around in there instead of in the clone of my forked repo. *face palm!*

**Comment by soerenthomsen** [comment]
Actually, I think I had the same issue once and @jbusecke had to help me out of this. So better we make sure the contribution guide is clear to avoid this for others.

**Comment by jbusecke** [comment]
Do you think that this is figured out now? Basically you want to think of your personal fork (`origin`) just a conduit/connection to the original repo (`upstream`). I would not recommend to use your fork for anything else than testing/active development. Each time you want to make some changes you should:
1. Sync your local clone of the forked repo ('origin') with the central repo (`upstream`).
2. Once you are synced, you make your changes and commit them on a new branch. 
3. That branch is then pushed to `origin` (and from there you can do a PR in the github interface)
4. The local clone of `origin` can then be left alone until your next change **If you are not using it for production work** (which you shouldn't normally)

I think what you have in #109 is generally good.
