### ISSUE TITLE
Change the way warnings are raised

### ISSUE THREAD

**Issue by isgiddy** [GliderToolsCommunity/GliderTools#126]
Warnings are currently raised as `raise UserWarning("warning")`, this method is incompatible with pytest to assert warnings which looks something like this.
```
with pytest.warns(UserWarning): # this line will fail if the command below does not actually raise a warning
        function(**args)
```
 For the above test to work, the warning needs to output a class UserWarning.
Suggest that warnings should rather be raised using `warnings.warn("warning", UserWarning)`

**Comment by jbusecke** [comment]
Good idea. Would you be up to submitting a PR, @isgiddy?

Just our of curiosity though, I would like if there was a reason to implement warnings this way (cc @lukegre)?

**Comment by MartinMohrmann** [comment]
BTW: There is one deprecation warning raised by pytest that I did not address yet (on purpose):
```
glidertools/load/seaglider.py:587: 7 warnings
tests/test_imports.py: 3 warnings
  /home/coffee/VOTO/code/glidertools/glidertools/load/seaglider.py:587: PendingDeprecationWarning: dropping variables using `drop` will be deprecated; using drop_vars is encouraged.
    df.reset_index(drop=True)
```
However, the recommended .drop_indexes() function that should be used in future has not made it into the stable xarray releases yet I think, so this will be fixed later, when xarray has moved on with a new stable release.
