### ISSUE TITLE
Edit on github button not working in the API section

### ISSUE THREAD

**Issue by dhruvbalwada** [GliderToolsCommunity/GliderTools#131]
The "edit on github" button/link on the top right of the page does not seem to be working when I am looking at the individual functions in the API page (eg https://glidertools.readthedocs.io/en/latest/_generated/glidertools.mapping.grid_data.html#glidertools.mapping.grid_data). 

When I click on it I get redirected to pages like (for example): https://github.com/GliderToolsCommunity/GliderTools/blob/master/docs/_generated/glidertools.mapping.grid_data.rst , which do not exist.

**Comment by jbusecke** [comment]
I believe this is an autogenerated page, and as such does not exist in the repo. What do you want to change?

**Comment by dhruvbalwada** [comment]
I see. I did not realize that the "edit on github" links were not meant to work on the API pages. I assumed maybe it was a structuring problem. That's ok. We can close this.

**Comment by jbusecke** [comment]
But this must have been prompted by an issue with the page? Or are you just clicking random buttons for fun 😆

**Comment by dhruvbalwada** [comment]
I was on the grid_data API page, and wanted to go look at the underlying code on the repo. So was hoping that the button would take me there, but I guess not.
