### ISSUE TITLE
Add "Gothenburg University", OceanGliders Best Practices to readme?

### ISSUE THREAD

**Issue by soerenthomsen** [GliderToolsCommunity/GliderTools#142]
### Discussed in https://github.com/GliderToolsCommunity/GliderTools/discussions/139

<div type='discussions-op-text'>

<sup>Originally posted by **soerenthomsen** September 14, 2021</sup>
Dear GliderToolsCommunity, 

in the readme file it is written at the moment that GliderTools: "We provide examples and demonstrate best practices as developed by the SOCCO Group." 

I suggest to add "Gothenburg University" and something that we aim to implement Best Practices developed by OceanGliders at the moment and refer to the new [OceanGlidersCommunity](https://github.com/OceanGlidersCommunity) repo ? 
in particular the planed refactoring on oxygen will be largely based on this [OceanGliders Ocean SOP](https://github.com/OceanGlidersCommunity/Oxygen_SOP).

What do you think? @lukegre @callumrollo @isgiddy @tjryankeogh @tomhull @jbusecke @callumrollo 
@bastienqueste and others? </div>

**Comment by soerenthomsen** [comment]
Before closing this I will also make a session to sync the docs with the GitHub readme. At the moment we have too very similar introductions here which are often not in phase and require to be updated separately...

**Comment by soerenthomsen** [comment]
@callumrollo we should also mention your funding source here in acknowledgement in my view.

**Comment by callumrollo** [comment]
That would be cool. I am employed by [VOTO](https://voiceoftheocean.org/en/) (Voice of the Ocean foundation). Just VOTO is fine though

**Comment by soerenthomsen** [comment]
Lets do it after the CI issue is fixed.

**Comment by soerenthomsen** [comment]
Now that the CI is fixed. 
@callumrollo do you want to ad VOTO?
