### ISSUE TITLE
CI fails for a different reason now!

### ISSUE THREAD

**Issue by jbusecke** [GliderToolsCommunity/GliderTools#149]
**Describe the bug**
The CI was previously failing with the error described in #136, but in the latest CI it fails for a different reason!
As you can see [here](https://github.com/GliderToolsCommunity/GliderTools/runs/4212126874?check_suite_focus=true) this now fails at the package installation step. 

This worries me a bit, I dont understand how this could have happened when only PRs with all checks passing are merged...

I am still trying to trace down the origin of the bug, but in the meantime I think we should prevent commits that were not introduced by PRs (there are quite a bunch of them [here](https://github.com/GliderToolsCommunity/GliderTools/commits/master)), just to keep things organized. Is that ok with everyone?

We should also agree on not merging anything unless the CI is working again to prevent this in the future. 

With regards to the bug, it seems it is some sort of issue with whitespaces?

**Comment by soerenthomsen** [comment]
Yes totally fine for me. I think I can also not commit without making a pull-request and for now just made edits to the docs.

**Comment by soerenthomsen** [comment]
There is one commit by @callumrollo related to white space:
https://github.com/GliderToolsCommunity/GliderTools/commit/c11c5bf58a8d2af6f53fc65936173e6de407c9b4

**Comment by soerenthomsen** [comment]
@jbusecke this can be closed now or?
