### ISSUE TITLE
DOCS: needed documentation updates after release v2022.12.13 

### ISSUE THREAD

**Issue by soerenthomsen** [GliderToolsCommunity/GliderTools#159]
Thanks @MartinMohrmann and @callumrollo for your epic work on the new [release v.2022.12.13](https://github.com/GliderToolsCommunity/GliderTools/releases/tag/v2022.12.13). 

In this issue we collect the all updates within the documentation needed after the release v2022.12.13 is final. 

- [x] [what's new](https://glidertools.readthedocs.io/en/latest/whats-new.html)
- [x] aligning readme.rst and index.rst (i.e. Python 3.8+), [ ] ideally we find a way to avoid that content has to be copied/duplicated
- [x] [zenodo link in readme.rst](https://github.com/GliderToolsCommunity/GliderTools/edit/master/README.rst) does not work at the moment 
- [x] [conda badge in readme.rst](https://github.com/GliderToolsCommunity/GliderTools/edit/master/README.rst), add new link
- [x] [pip badge in readme.rst](https://github.com/GliderToolsCommunity/GliderTools/edit/master/README.rst), add new link
- [x] update @callumrollo affiliation in [authors.md](https://github.com/GliderToolsCommunity/GliderTools/blob/master/docs/authors.md)
- [ ] replace [wish list](https://github.com/GliderToolsCommunity/GliderTools/blob/master/docs/wishlist.md) with suggestion to open an issue instead as there we can see how much traction a certain issue gets to prioritise
- [x] update and move [release instructions](https://github.com/GliderToolsCommunity/ReleaseInstructions), own privat repo at the moment visible for maintainers, not ideal to have an own repo for this i.e, as we also have a demo repo and I suggest to add it to the GliderTools, docs under how to make contributions
- please add all places missing so far

**Comment by callumrollo** [comment]
The packaging of v2022.12.13 has been completed. I have successfully installed it both in pip and conda.

I will start working on these issues now. I will take the links and badges in readme as well as my affiliation in authors for a start

**Comment by MartinMohrmann** [comment]
Hi, I think the documentation is progressing well - Callum is updating the Demo-Notebook, and we wrote some lines in "What's new" and the documentation files. However, I can't figure out how to make my documentation appear at [https://glidertools.readthedocs.io/en/latest/api.html](https://glidertools.readthedocs.io/en/latest/api.html). That seems to be automated somehow. Can't figure out why my documentation strings, that are already merged into the code, e.g. for utils.mask_below_depths wont show up. 
Help!
