### ISSUE TITLE
Brunt-Vaisalla function not returning anything

### ISSUE THREAD

**Issue by tjryankeogh** [GliderToolsCommunity/GliderTools#16]
**Describe the bug**
When using the function it does not return an array of N2.

**Additional context**
It appears as if the pad_nan function is the issue. When using the GSW function alone it returns a N2 array.

**Comment by luke-gregor** [comment]
Yo @tjryankeogh !
I don't think I'll be getting around to these issues, just too far from what I'm doing at the moment. Do you think you'll be able to give it a shot?
