### ISSUE TITLE
Update contribution guide

### ISSUE THREAD

**Issue by dhruvbalwada** [GliderToolsCommunity/GliderTools#18]
I was unable to follow the contribution guide. 
- Is the bit about pre-commit from a previous version? 
- where is the CHANGELOG.rst? or docs/source/contributors.rst?

**Comment by luke-gregor** [comment]
Hi @dhruvbalwada ,

Thanks for picking up on this. I've changed the contributors and changelog now lives in `docs/history.md`. I have to update the HOWTOCONTRIBUTE.md for the history changes. But just follow the examples in that document. 

Re pre-commit, can you be a bit more specific?

**Comment by luke-gregor** [comment]
Solved with PR #26
