### ISSUE TITLE
Cannot merge data

### ISSUE THREAD

**Issue by LewisDrysdale** [GliderToolsCommunity/GliderTools#181]
I am suddenly unable to merge any seaglider data. This includes data that I have previously successfully merged.  I'm not a Pandas expert so I'm finding this quite difficult to debug. I thought it may be an issue with some of the glider files but I've been sub setting the files randomly and it is still an issue. Any help would be much appreciated, or to know if anyone else has experience this issue?

I have gone back to follow the exact instructions from the [Glider Tools docs ](https://glidertools.readthedocs.io/en/latest/index.html)

Screenshot example:

![image](https://user-images.githubusercontent.com/45363219/234867323-45312630-627d-4eed-8b24-37df6521e3c9.png)

Environment.yml file I am using

name: oceanglider
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.1
  - jupyter
  - pandas=1.5
  - scikit-learn
  - scipy=1.5.3
  - glidertools
  - cmocean
  - pip=23.0
  - jupyterlab
  - ipympl 
  - pip:
      - cftime==1.6.2
      - gsw==3.6.16
      - markdown==3.3.4
      - markdown2==2.4.2
      - markdown2pdf==0.1.4
      - mat4py==0.5.0
      - motuclient==1.8.8
      - scp==0.14.4
      - seaborn==0.12.2
      - seawater==3.3.4
      - cf-python==3.14.1
prefix: C:\Users\sa01ld\Miniconda3

**Comment by callumrollo** [comment]
Hi Lewis. Are you able to run the example in the demo notebooks with the Seaglider files that ship with the package? If not, what error message do you get there?

What are the dimensions of the unmerged dataframes that it returns?

**Comment by LewisDrysdale** [comment]
You can find some of the data I am working with here https://thredds.sams.ac.uk/thredds/catalog/sg534/mission_5/catalog.html

**Comment by callumrollo** [comment]
Yep, I think that's the case. If you want to get a time-indexed pandas dataframe from the xarray dataset returned by the load merge function, you can do something like:
```python
merged = ds_dict['sg_data_point']
df = merged.to_pandas()
df.index = df["ctd_time_dt64"]
df = df.drop("ctd_time_dt64", axis=1)
```
