### ISSUE TITLE
grid_data not producing sorted dives axis

### ISSUE THREAD

**Issue by dhruvbalwada** [GliderToolsCommunity/GliderTools#19]
**Describe the bug**
When I use grid_data to grid data onto a uniform pressure axis, I am sometimes get a dives coordinate that is not properly sorted. 

**To Reproduce**
When I run `temp_grided_659 = gt.grid_data(ds_659.dives, ds_659.pressure, ds_659.temperature)`
I get a dives axis that looks like : 
![Screen Shot 2020-09-21 at 5 58 26 PM](https://user-images.githubusercontent.com/18236610/93835451-2061ca00-fc34-11ea-9b46-aff510da9d81.png)

I am not sure if this is because of some peculiarity on my data, or if the grid_data function should have an added sorting step.

**Comment by luke-gregor** [comment]
Hi @dhruvbalwada, 
Would you be happy giving this a go? 
I don't have time to work on all the issues anymore :-(  as I'm no longer working with glider data.
