### ISSUE TITLE
`gt.optics.sunrise_sunset` fails at high lats

### ISSUE THREAD

**Issue by lukegre** [GliderToolsCommunity/GliderTools#37]
**Describe the bug**
At high latitudes during times when the sun does not rise or set, the function fails. 

**To Reproduce**

```python 
import numpy as np
import glidertools as gt

time = [np.datetime64("2000-12-21"), np.datetime64("2000-06-21")]
lat = (-80, 80)
lon = (0, 0)
sunrise, sunset = gt.optics.sunset_sunrise(time, lat, lon)
```

**Expected behavior**
If it is light all the time, then return sunrise as 00:00 and sunset as 23:59
Similarly, if it is dark, sunrise would be at 11:59 and sunset at 12:00

**Comment by isgiddy** [comment]
This issue has been resolved along with the switch from astral to skyfield (Pull Request #121  )
