### ISSUE TITLE
setup.py pins dependency on netcdf4 1.5.4

### ISSUE THREAD

**Issue by robfatland** [GliderToolsCommunity/GliderTools#38]
**Describe the bug**
`import glidertools` produces an error to the effect of `you have netcdf4 1.5.5.1 and you need to use 1.5.4`. 

**To Reproduce**
I'm on an Ubuntu system, using a conda environment built from a `.yml` file. I installed `glidertools` using `pip` as instructed. Working in a Jupyter notebook I get the version issue as above. 

**Attempt to Remedy**
I added `    - netcdf4=1.5.4` to my `.yml` file and did the pip install from the activated environment. This also fails: The notebook server starts but an actual notebook open hits some sort of file not found error. 

So... it would be great to revisit this dependency! tx -rob

**Comment by jbusecke** [comment]
I belive this was closed via #54. Closing
