### ISSUE TITLE
Docs are not building?

### ISSUE THREAD

**Issue by jbusecke** [GliderToolsCommunity/GliderTools#41]
It seems that Readthedocs has [not built](https://readthedocs.org/projects/glidertools/builds/) for recent PRs (e.g. #40).

I would also suggest activating the [Pull Request Build Feature](https://docs.readthedocs.io/en/stable/pull-requests.html). 
Happy to help where I can. 

@luke-gregor Could you check if there is a way to reconnect the repo to Readthedocs?

cc @soerenthomsen

**Comment by soerenthomsen** [comment]
Glad to support this!

**Comment by luke-gregor** [comment]
Thanks for pointing this out. I've enabled the [Pull Request Build Feature](https://docs.readthedocs.io/en/stable/pull-requests.html). Should automatically build from now on. Docs are also passing 😅 

Let me know if it's not working

**Comment by jbusecke** [comment]
Thanks a lot @luke-gregor
