### ISSUE TITLE
Creat a conda-forge recipe

### ISSUE THREAD

**Issue by callumrollo** [GliderToolsCommunity/GliderTools#45]
Would increase the accessibility of the tool. In my experience, many more scientists use conda than pip

I have made one much simpler conda-forge recipe before. @jbusecke might be able to help

**Comment by jbusecke** [comment]
I would like to have more than one recipe maintainer. @callumrollo @dhruvbalwada @lukegre, would you be willing to help out here? This should be minimal work. Usually its just merging a PR once a new version is published.

**Comment by callumrollo** [comment]
@jbusecke I'm happy to be a maintainer

**Comment by jbusecke** [comment]
Amazing. Thanks @callumrollo.

**Comment by jbusecke** [comment]
I have started https://github.com/conda-forge/staged-recipes/pull/14282. 
For anyone curious, I have a short write up of the procedure [here](https://github.com/jbusecke/guides/blob/master/publishing.md)

**Comment by jbusecke** [comment]
Ok that was quite a bit of work, but the recipe is building over at https://github.com/conda-forge/staged-recipes/pull/14282.

Waiting for them to merge and then we have a conda-forge package!

**Comment by jbusecke** [comment]
Thats it! You can now use conda to install glidertools.

**Comment by Thomas-Moore-Creative** [comment]
@jbusecke strikes again for maximum community goodness!
