### ISSUE TITLE
Add short example notebooks

### ISSUE THREAD

**Issue by callumrollo** [GliderToolsCommunity/GliderTools#48]
**Rationale**
The only current notebook is huge and overwhelming. A set of small notebooks for specific, common tasks would be much more appealing to the casually interested scientist

**How the user would call this functionality.**
Ideally by clicking a button in the README that launches a Binder notebook e.g. "Intro to glider tools" or "correct for chlorophyll quenching" 
    
**Outline what is needed for this feature**
Should write notebooks for features that
- Are applicable to many users
- Have a stable implementation
- Can be easily binderised

I think porting the package to conda-forge (#45) will make this easier. In my experience, binder prefers conda packages to pip.

This is an issue from the #46 wishlist

**Comment by soerenthomsen** [comment]
My suggestion is to make an example related to the optics / chlorophyll quenching part which seem to be well developed.

**Comment by soerenthomsen** [comment]
Great looking forward to these example notebooks! Will you focus on the optics part of GliderTools? It is very advanced! @tjryankeogh

**Comment by callumrollo** [comment]
I have created a repo for the notebooks here:
https://github.com/callumrollo/glidertools-demo
Closing this Issue

**Comment by jbusecke** [comment]
Awesome! Should we add a link to the binder/repo to the README and/or docs?

**Comment by dhruvbalwada** [comment]
I think that would be nice. If @callumrollo is interested maybe the demo repo can live in the community (https://github.com/GliderToolsCommunity) but as a separate object from the Glidertools.

**Comment by jbusecke** [comment]
Thats a great idea!

**Comment by callumrollo** [comment]
Good shout Dhruv, I've just transferred it
