### ISSUE TITLE
Python Version 3.6+ (in docs) vs. 3.7 GitHub 

### ISSUE THREAD

**Issue by soerenthomsen** [GliderToolsCommunity/GliderTools#70]
I am still to insecure to make pull requests directly thus this issue: 

In the docs it it written: 
Glider tools is a Python **3.6+** package designed ... 
https://glidertools.readthedocs.io/en/latest/

And on GitHub in the  README.rst 
Glider tools is a Python **3.7** package designed ... 

This confused me and I guess it has to be the same or?

@lukegre @jbusecke @dhruvbalwada

**Comment by lukegre** [comment]
I've added Python 3.6, 3.7 and 3.8 to the testing so that the GT is truly a 3.6+ package. 

That being said, you make a good point. The README is severely outdated. So, something to add to the list 😄

**Comment by soerenthomsen** [comment]
Ok great. Thanks for explaining! @lukegre

**Comment by jbusecke** [comment]
I would not necessarily mention this specifically in the docs, since we might change that in the future. This should live in the packaging info IMO.
