### ISSUE TITLE
Problems with Pypi authentication

### ISSUE THREAD

**Issue by jbusecke** [GliderToolsCommunity/GliderTools#87]
The new deployment action has problems [authenticating with pypi](https://github.com/GliderToolsCommunity/GliderTools/runs/2229248583?check_suite_focus=true#step:5:273). 

@lukegre Could you check/update the repo secrets. In the long term it might be more efficient if could you add me as a maintainer on the pypi side (username: jbusecke)?

Thanks.

**Comment by lukegre** [comment]
@jbusecke added you as an owner to PyPI.
