### ISSUE TITLE
Is git lfs still in use?

### ISSUE THREAD

**Issue by jbusecke** [GliderToolsCommunity/GliderTools#92]
I have been banging my head against the wall, why the automatic [deployment workflow](https://github.com/GliderToolsCommunity/GliderTools/actions/runs/702241994) keeps producing a dirty version number [e.g. here](https://github.com/GliderToolsCommunity/GliderTools/runs/2229943052?check_suite_focus=true#step:7:266).

It seems that the file [`notebook/Demo_GT.ipynb`](https://github.com/GliderToolsCommunity/GliderTools/runs/2229943052?check_suite_focus=true#step:4:10) is modified during the workflow. 

I do not quite understand how that is happening, but I suspect that it might have something to do with git lfs?
Do we need to use that? Or could we just commit the notebook as is and remove `.gitattributes`?

cc @lukegre

**Comment by lukegre** [comment]
Nope, we're not using it. Feel free to remove `.gitattributes`

Had hopes to remove the big notebook file from the repo - will be addressed with the binder examples 👍

**Comment by jbusecke** [comment]
That did the trick!
