### ISSUE TITLE
Switch from seawater to gsw

### ISSUE THREAD

**Issue by callumrollo** [GliderToolsCommunity/GliderTools#95]
Is there a reason GliderTools still uses the `seawater` toolbox? I believe this is deprecated in favour of `gsw`

There are switch statements in the toolbox functions to use `gsw` if available. The explanation in physics.py appears to be that, unlike `seawater`, `gsw` is not available in Python 2.x. However, glider tools requires Python >= 3.7 so I don't see what value `seawater` adds.

Note: Filipe at condaforge suggests moving from `seawater` to `gsw`  https://github.com/conda-forge/staged-recipes/pull/14282/files/d9f8d646e5a7d7e36ddacd45612382e0837e8b1e#r604367193

This is particularly compelling seeing as he is the maintainer of `seawater` https://pypi.org/project/seawater/

**Comment by dhruvbalwada** [comment]
I agree that we can move over, and remove support for `seawater`. I have only ever used `gsw` with GT.
